<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
	
		<div class="container">
		
			<!-- Bouton responsive pour activer le menu principal -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span>
			</a> 
			
			<!-- Logo -->
			<a class="brand" href="<?php echo $this->baseUrl(); ?>">Hades</a>
			
			<!-- menu principal -->
			<div class="nav-collapse collapse">
				
			</div>
			
		</div>
		
	</div>
</div>
