<?php echo $this->doctype(); ?>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <?php echo $this->headMeta()
                        ->prependName('viewport', 'width=device-width, initial-scale=1.0')
                        ->prependHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
                        ->setCharset('utf-8')
        ?>
        
		<?php echo $this->headTitle('HADES')->setSeparator(' | ')->setAutoEscape(false) ?>
		
        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        				->prependStylesheet($this->basePath() . '/css/main.css')
        				->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')                 
        ?>

        <!-- Head Scripts -->
        <?php echo $this->headScript()
        				->prependFile($this->basePath() . '/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js' ) 
        ?>
    </head>
    
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">Vous utilisez un navigateur <strong>obsolète</strong>. Veuillez le <a href="http://browsehappy.com/">mettre à jour</a> ou <a href="http://www.google.com/chromeframe/?redirect=true">activer Google Chrome Frame</a> pour améliorer votre expérience de navigation.</p>
        <![endif]-->


        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                
                	<!-- Bootstrap Responsive : button to collapse menu on small screens -->
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    
                    <a class="brand" href="<?php $this->url('home') ?>">HADES</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php $this->url('home') ?>">Accueil</a></li>
                        </ul>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="container">
        
			<?php echo $this->content; ?>
            
			<hr />
            <footer>
                <p>&copy; HADES 2013</p>
            </footer>

        </div>

        <!-- Inline Scripts -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $this->basePath() ?>/js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
		
		<?php echo $this->inlineScript()
						->prependFile($this->basePath() . '/js/main.js' ) 
						->prependFile($this->basePath() . '/js/vendor/bootstrap.min.js' )
		?>


    </body>
</html>
