<div class="hero-unit">
	<h2>Bienvenue sur HADES</h2>
</div>


<a class="button add" href="<?php echo $this->url(array('controller'=>'index','action'=>'index','module'=>'admin'));?>">Administration</a>

<h3>Liste des questionnaires : </h3>
<?php foreach($this->questionnaires as $questionnaire): ?>
<p>Nom : <?= $questionnaire->name ?> -  Durée : <?= $questionnaire->timer ?> - Nombre de question : <?= $questionnaire->nbQuery ?></p>
<?php endforeach;  ?>

